name: Build Kucheza firmware
on:
  workflow_dispatch:
  push:
    branches:
      - kucheza-vial
      - vial
jobs:
  Build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli:latest
    strategy:
      fail-fast: false
      matrix:
        keymap: [amacleod, default]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install QMK python dependencies
        run: /opt/uv/tools/qmk/bin/python3 -m pip install -q -r requirements.txt

      - name: Build firmware
        run: make fingerpunch/kucheza:${{ matrix.keymap }}

      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: kucheza_${{ matrix.keymap }}
          path: |
            *.uf2
